apiVersion: v1
kind: Secret
metadata:
  name: overleaf-git-bridge-s3
  namespace: overleaf
type: Opaque
stringData:
  OVERLEAF_FILESTORE_S3_ACCESS_KEY_ID: abcdefghijklm
  OVERLEAF_FILESTORE_S3_SECRET_ACCESS_KEY: abcdefghijklm1234567890abcdefghijklm1234567890
  